name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Ensure this is the correct branch for your repository.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # Ensure this is the correct directory for your site's contents.
